<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-10-24">

<title>Ejercicios de estadística descriptiva multivariante</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="practica3_files/libs/clipboard/clipboard.min.js"></script>
<script src="practica3_files/libs/quarto-html/quarto.js"></script>
<script src="practica3_files/libs/quarto-html/popper.min.js"></script>
<script src="practica3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="practica3_files/libs/quarto-html/anchor.min.js"></script>
<link href="practica3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="practica3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="practica3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="practica3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="practica3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#enunciado-y-datos" id="toc-enunciado-y-datos" class="nav-link active" data-scroll-target="#enunciado-y-datos">Enunciado y datos</a>
  <ul class="collapse">
  <li><a href="#apartado-1" id="toc-apartado-1" class="nav-link" data-scroll-target="#apartado-1">Apartado 1</a></li>
  <li><a href="#apartado-2" id="toc-apartado-2" class="nav-link" data-scroll-target="#apartado-2">Apartado 2</a></li>
  <li><a href="#apartado-3" id="toc-apartado-3" class="nav-link" data-scroll-target="#apartado-3">Apartado 3</a></li>
  <li><a href="#apartado-4" id="toc-apartado-4" class="nav-link" data-scroll-target="#apartado-4">Apartado 4</a></li>
  <li><a href="#apartado-5" id="toc-apartado-5" class="nav-link" data-scroll-target="#apartado-5">Apartado 5</a></li>
  <li><a href="#apartado-6" id="toc-apartado-6" class="nav-link" data-scroll-target="#apartado-6">Apartado 6</a></li>
  <li><a href="#apartado-7" id="toc-apartado-7" class="nav-link" data-scroll-target="#apartado-7">Apartado 7</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ejercicios de estadística descriptiva multivariante</h1>
<p class="subtitle lead">20582- Análisis de Datos para el GMAT</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Dídac Capó Peña</strong>:</p>
<p><a href="https://github.com/WatCadet/PRACTICA_3_AD">Ver en GitHub</a></p>
<section id="enunciado-y-datos" class="level2">
<h2 class="anchored" data-anchor-id="enunciado-y-datos">Enunciado y datos</h2>
<p>Una empresa quiere analizar si existe relación entre las ventas de sus productos, la inversión en publicidad y la satisfacción del cliente. Los datos que corresponden a las ventas han sido registrados en miles de unidades, el gasto en publicidad en miles de euros y la puntuación de satisfacción del cliente en una escala de 1 a 10 para 30 productos, los puedes descargar en el siguiente enlace: <a href="https://github.com/igmuib/Practica_AD/blob/main/datos_empresa.csv">datos empresa</a></p>
<section id="visualizar-y-leer-los-datos" class="level4">
<h4 class="anchored" data-anchor-id="visualizar-y-leer-los-datos">Visualizar y leer los datos:</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 5
   Producto Ventas Publicidad Satisfaccion_cliente Marca
      &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;
 1        1    150         30                  8.2 A    
 2        2    200         40                  9.1 B    
 3        3    180         35                  8.7 C    
 4        4    120         25                  7.5 A    
 5        5    170         32                  8   B    
 6        6    140         28                  7.9 C    
 7        7    160         30                  8.5 A    
 8        8    210         42                  9.3 B    
 9        9    130         27                  7.8 C    
10       10    155         30                  8.1 A    
# ℹ 20 more rows</code></pre>
</div>
</div>
</section>
<section id="apartado-1" class="level3">
<h3 class="anchored" data-anchor-id="apartado-1">Apartado 1</h3>
<p>Organiza el conjunto de datos en una matriz, donde cada fila corresponda a un producto y cada columna a una variable, siendo la variable “Producto” únicamente un identificador. A continuación, presenta la matriz de dispersión entre las variables, utilizando puntos coloreados según el tipo de marca (consulta la sección 2.4.2 de los apuntes). Comenta los resultados obtenidos, prestando especial atención a lo que indican los valores de las correlaciones entre las variables.</p>
<section id="respuesta" class="level4">
<h4 class="anchored" data-anchor-id="respuesta">Respuesta</h4>
<p>Nuestra matriz de datos, que llamaremos <span class="math inline">\(X\)</span>, es la siguiente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 4
   Ventas Publicidad Satisfaccion_cliente Marca
    &lt;dbl&gt;      &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;
 1    150         30                  8.2 A    
 2    200         40                  9.1 B    
 3    180         35                  8.7 C    
 4    120         25                  7.5 A    
 5    170         32                  8   B    
 6    140         28                  7.9 C    
 7    160         30                  8.5 A    
 8    210         42                  9.3 B    
 9    130         27                  7.8 C    
10    155         30                  8.1 A    
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>La Matriz de dispersión entre las variables es la siguiente. Hemos utilizado distinción en colores segun el tipo de marca.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>a<span class="sc">$</span>Marca <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(a<span class="sc">$</span>Marca)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(a, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">color =</span> Marca, <span class="at">fill =</span> Marca)) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En las <span class="math inline">\(\textbf{Celdas de la Diagonal Principal}\)</span> encontramos la distribución por Marca (A, B, C) de cada variable de forma individual. Los gráficos de densidad indican cómo se distribuyen los valores para cada grupo (Marca A, Marca B, Marca C). Las áreas en diferentes colores (rojo para Marca A, azul para Marca B y verde para Marca C) nos dan una idea de la dispersión y concentración de los valores. Las variables categóricas, como “Marca”, se muestran como diagramas de barras, donde vemos que hay la misma cantidad de cada tipo.</p>
<p>En las <span class="math inline">\(\textbf{Celdas Inferiores}\)</span> se muestran gráficos de dispersión para cada par de variables cuantitativas. Los puntos están coloreados según la variable Marca, lo cual permite observar visualmente si las tres marcas se comportan de manera diferente en términos de correlación. Por ejemplo: La celda que relaciona Ventas y Publicidad muestra cómo se comportan estas variables, y podemos notar una tendencia clara creciente, lo cual sugiere una fuerte correlación positiva.</p>
<p>En las <span class="math inline">\(\textbf{Celdas Superiores}\)</span> tenemos el coeficiente de correlación entre los pares de variables cuantitativas. Los coeficientes de correlación están coloreados y desglosados por cada marca (A, B, C). Los números indican el valor de la correlación entre las variables. En los tres casos la correlación es <span class="math inline">\(&gt;0\)</span>, por lo tanto, para todo par de variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> las correlaciones son positivas. Podemos concluir que si <span class="math inline">\(x_i &gt; x_j\)</span>, entonces <span class="math inline">\(y_i\)</span> tiende a ser más grande que <span class="math inline">\(y_j\)</span>.</p>
<p>En las <span class="math inline">\(\textbf{Celdas con Boxplots y Diagramas de Barras}\)</span> se está relacionando una variable continua con la categórica (Marca). Estas celdas, que están relacionadas con la variable Marca, contienen diagramas de caja (boxplots) o diagramas de barras. Los boxplots permiten visualizar la mediana, los cuartiles y los posibles valores atípicos (outliers) para cada variable continua (Ventas, Publicidad, Satisfacción_cliente) en relación con cada Marca (A, B, C). Vemos que, para las tres variables cuantitativas, los elementos de la Marca B tienden a tener mayor mediana.</p>
</section>
</section>
<section id="apartado-2" class="level3">
<h3 class="anchored" data-anchor-id="apartado-2">Apartado 2</h3>
<p>Calcula la matriz de datos centrada y el vector de medias con las formas matriciales estudiada en clase de teoría. Interpreta el vector de medias en el contexto del problema.</p>
<section id="respuesta-1" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-1">Respuesta</h4>
<p>El vector de medias, para las variables cuantitativas, és el siguiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>X_q <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="dv">4</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>X_q <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(X_q) </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>x_barra <span class="ot">=</span> <span class="fu">colMeans</span>(X_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math inline">\(\overline{x} = (164, 32.33, 8.35)\)</span></p>
<p>Tambien podemos obtener el mismo vector aplicando <span class="math inline">\(\overline{x}^T = \frac{1}{n}1^TX\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="dv">30</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>unos  <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, n)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>x_barra2 <span class="ot">=</span> (<span class="dv">1</span><span class="sc">/</span>n) <span class="sc">*</span> unos <span class="sc">%*%</span> X_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El resultado es el mismo.</p>
<p>La media de las ventas es de <span class="math inline">\(164\)</span> miles de unidades, la media del gasto en publicidad es de <span class="math inline">\(32.33\)</span> miles de euros y la media de la puntuación de satisfacción del cliente es de <span class="math inline">\(8.35\)</span>.</p>
<p>Ahora calculemos la matriz de datos centrados de dos maneras distintas, ya que <span class="math inline">\(\tilde{X}= X - 1\overline{x}^T = HX\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>X_tilde <span class="ot">=</span> X_q <span class="sc">-</span> unos <span class="sc">%*%</span> x_barra2</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>X_tilde</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Ventas Publicidad Satisfaccion_cliente
 [1,]    -14 -2.3333333           -0.1466667
 [2,]     36  7.6666667            0.7533333
 [3,]     16  2.6666667            0.3533333
 [4,]    -44 -7.3333333           -0.8466667
 [5,]      6 -0.3333333           -0.3466667
 [6,]    -24 -4.3333333           -0.4466667
 [7,]     -4 -2.3333333            0.1533333
 [8,]     46  9.6666667            0.9533333
 [9,]    -34 -5.3333333           -0.5466667
[10,]     -9 -2.3333333           -0.2466667
[11,]    -19 -4.3333333           -0.7466667
[12,]     31  5.6666667            0.6533333
[13,]    -29 -6.3333333           -0.6466667
[14,]     41  8.6666667            0.8533333
[15,]      1  0.6666667            0.2533333
[16,]    -14 -2.3333333           -0.1466667
[17,]     36  7.6666667            0.7533333
[18,]     16  2.6666667            0.3533333
[19,]    -44 -7.3333333           -0.8466667
[20,]      6 -0.3333333           -0.3466667
[21,]    -24 -4.3333333           -0.4466667
[22,]     -4 -2.3333333            0.1533333
[23,]     46  9.6666667            0.9533333
[24,]    -34 -5.3333333           -0.5466667
[25,]     -9 -2.3333333           -0.2466667
[26,]    -19 -4.3333333           -0.7466667
[27,]     31  5.6666667            0.6533333
[28,]    -29 -6.3333333           -0.6466667
[29,]     41  8.6666667            0.8533333
[30,]      1  0.6666667            0.2533333</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="dv">30</span>) <span class="sc">-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">/</span>n, <span class="at">nrow =</span> <span class="dv">30</span>, <span class="at">ncol =</span> <span class="dv">30</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>X_tilde1 <span class="ot">=</span> H<span class="sc">%*%</span> X_q </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>X_tilde1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Ventas Publicidad Satisfaccion_cliente
 [1,]    -14 -2.3333333           -0.1466667
 [2,]     36  7.6666667            0.7533333
 [3,]     16  2.6666667            0.3533333
 [4,]    -44 -7.3333333           -0.8466667
 [5,]      6 -0.3333333           -0.3466667
 [6,]    -24 -4.3333333           -0.4466667
 [7,]     -4 -2.3333333            0.1533333
 [8,]     46  9.6666667            0.9533333
 [9,]    -34 -5.3333333           -0.5466667
[10,]     -9 -2.3333333           -0.2466667
[11,]    -19 -4.3333333           -0.7466667
[12,]     31  5.6666667            0.6533333
[13,]    -29 -6.3333333           -0.6466667
[14,]     41  8.6666667            0.8533333
[15,]      1  0.6666667            0.2533333
[16,]    -14 -2.3333333           -0.1466667
[17,]     36  7.6666667            0.7533333
[18,]     16  2.6666667            0.3533333
[19,]    -44 -7.3333333           -0.8466667
[20,]      6 -0.3333333           -0.3466667
[21,]    -24 -4.3333333           -0.4466667
[22,]     -4 -2.3333333            0.1533333
[23,]     46  9.6666667            0.9533333
[24,]    -34 -5.3333333           -0.5466667
[25,]     -9 -2.3333333           -0.2466667
[26,]    -19 -4.3333333           -0.7466667
[27,]     31  5.6666667            0.6533333
[28,]    -29 -6.3333333           -0.6466667
[29,]     41  8.6666667            0.8533333
[30,]      1  0.6666667            0.2533333</code></pre>
</div>
</div>
<p>En los dos casos obtenemos lo mismo</p>
</section>
</section>
<section id="apartado-3" class="level3">
<h3 class="anchored" data-anchor-id="apartado-3">Apartado 3</h3>
<p>Calcula la matriz de covarianzas y la matriz de correlaciones utilizando las formas matriciales vistas en la clase de teoría. A continuación, interpreta los resultados obtenidos para ambas matrices en el contexto del problema.</p>
<section id="respuesta-2" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-2">Respuesta</h4>
<p>Calculemos primero la matriz de covarianzas, <span class="math inline">\(S = \frac{1}{n} X^THX\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>X_transpuesta <span class="ot">&lt;-</span> <span class="fu">t</span>(X_q) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> (<span class="dv">1</span><span class="sc">/</span>n) <span class="sc">*</span> X_transpuesta <span class="sc">%*%</span> H <span class="sc">%*%</span> X_q</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>S</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Ventas Publicidad Satisfaccion_cliente
Ventas               767.33333 148.666667           15.5466667
Publicidad           148.66667  29.555556            3.0844444
Satisfaccion_cliente  15.54667   3.084444            0.3491556</code></pre>
</div>
</div>
<p>Revisemos que hemos obtenido bien los datos con la función <code>cov</code>. Recordemos que tenemos que multiplicar por <span class="math inline">\(\frac{n-1}{n}\)</span> para obtener la matriz de covarianzas a secas en lugar de la muestral,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(n<span class="dv">-1</span>)<span class="sc">/</span>n<span class="sc">*</span><span class="fu">cov</span>(X_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Ventas Publicidad Satisfaccion_cliente
Ventas               767.33333 148.666667           15.5466667
Publicidad           148.66667  29.555556            3.0844444
Satisfaccion_cliente  15.54667   3.084444            0.3491556</code></pre>
</div>
</div>
<p>Vemos que coinciden.</p>
<p>Notemos que todas las covarianzas son positivas, <span class="math inline">\(S_{X,Y} &gt; 0\)</span>, podemos concluir que si <span class="math inline">\(x_i &gt; x_j\)</span> entonces <span class="math inline">\(y_i\)</span> tiende a ser más grande que <span class="math inline">\(y_j\)</span>.</p>
<p>Calculemos ahora la matriz de correlaciones, <span class="math inline">\(R= D^{-1}SD^{-1}\)</span>:</p>
<p>Definimos <span class="math inline">\(D\)</span> como la matriz diagonal con las varianzas en la diagonal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>diagonal <span class="ot">&lt;-</span> <span class="fu">diag</span>(S)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>diagonal <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(diagonal)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">diag</span>(diagonal)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>D_inversa <span class="ot">&lt;-</span> <span class="fu">solve</span>(D)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>R <span class="ot">=</span> D_inversa <span class="sc">%*%</span> S <span class="sc">%*%</span> D_inversa</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>R</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]      [,2]      [,3]
[1,] 1.0000000 0.9871929 0.9498079
[2,] 0.9871929 1.0000000 0.9601695
[3,] 0.9498079 0.9601695 1.0000000</code></pre>
</div>
</div>
<p>Revisemos que hemos obtenido bien los datos con la función <code>cor</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(X_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Ventas Publicidad Satisfaccion_cliente
Ventas               1.0000000  0.9871929            0.9498079
Publicidad           0.9871929  1.0000000            0.9601695
Satisfaccion_cliente 0.9498079  0.9601695            1.0000000</code></pre>
</div>
</div>
<p>Vemos que coinciden.</p>
<p>Notemos que todas las correlaciones son positivas, <span class="math inline">\(R_{X,Y} &gt; 0\)</span>, podemos concluir que si <span class="math inline">\(x_i &gt; x_j\)</span> entonces <span class="math inline">\(y_i\)</span> tiende a ser más grande que <span class="math inline">\(y_j\)</span>.</p>
</section>
</section>
<section id="apartado-4" class="level3">
<h3 class="anchored" data-anchor-id="apartado-4">Apartado 4</h3>
<p>Calcula la matriz de correlaciones muestrales con la forma matricial estudiada en clase de teoría y revisa que lo has hecho bien con la función disponible de <code>R</code>. Interpreta los resultados obtenidos.</p>
<section id="respuesta-3" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-3">Respuesta</h4>
<p>Todo realizado en el apartado anterior.</p>
</section>
</section>
<section id="apartado-5" class="level3">
<h3 class="anchored" data-anchor-id="apartado-5">Apartado 5</h3>
<p>Calcula la varianza generalizada y la variación total del conjunto de datos numéricos que estamos estudiando. Interpreta los resultados obtenidos.</p>
<section id="respuesta-4" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-4">Respuesta</h4>
<p>Las definiciones de varianza generalizada y variación total són las siguientes,repectivamente:</p>
<p><span class="math display">\[|S| = \prod_i^p \lambda_i\]</span> <span class="math display">\[Tr(S)= \sum_i^p \lambda_i\]</span> donde los <span class="math inline">\(\lambda_i\)</span> són los valores propios de la matriz de covarianzas <span class="math inline">\(S\)</span>. Saquemos los valores propios de <span class="math inline">\(S\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>valores_propios <span class="ot">&lt;-</span> <span class="fu">eigen</span>(S)<span class="sc">$</span>values</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>valores_propios</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 796.47946744   0.73162695   0.02695006</code></pre>
</div>
</div>
<p>Por tanto, la varianza generalizada es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(valores_propios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.70449</code></pre>
</div>
</div>
<p>Y, la variación total:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(valores_propios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 797.238</code></pre>
</div>
</div>
<p>La variación total representa la dispersión individual de las variables. Es decir, mide cuánto varía cada variable sin considerar las relaciones entre ellas(ignora las covarianzas). Mientras que la varianza generalizada mide la variabilidad conjunta de las variables, es decir, cuánto varían las variables juntas. En este caso, la varianza generalizada es 15.7 y la variación total 797.24. Esto indica que las tres variables tienen una cantidad significativa de variación individual(como refleja la variación total), però estan fuertemente correlacionadas entre sí, lo que reduce la dispersión conjunta. Esto podria implicar que hay redundancia entre las variables: aunque parecen variar de manera considerable por separado, mucha de esa variación se debe a relaciones communes entre variables. Por ejemplo , tanto las ventas como la satisfacción del cliente podrían depender fuertemnete de la publicidad, haciendo que sus variaciones esten alineadas.</p>
</section>
</section>
<section id="apartado-6" class="level3">
<h3 class="anchored" data-anchor-id="apartado-6">Apartado 6</h3>
<p>Calcula los vectores de medias y las matrices de correlacioes muestrales para cada marca de productos utilizando las funciones que están disponibles en <code>R</code> y <code>tidyverse</code>. Comenta los resultados obtenidos.</p>
<section id="respuesta-5" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-5">Respuesta</h4>
<p>Empezemos con el vector de medias:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>medias <span class="ot">&lt;-</span> data_analisis2 <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Marca) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ventas_media =</span> <span class="fu">mean</span>(Ventas),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Publicidad_media =</span> <span class="fu">mean</span>(Publicidad),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Satisfaccion_cliente_media=</span> <span class="fu">mean</span>(Satisfaccion_cliente) </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>medias</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Marca Ventas_media Publicidad_media Satisfaccion_cliente_media
  &lt;chr&gt;        &lt;dbl&gt;            &lt;dbl&gt;                      &lt;dbl&gt;
1 A              144             28.2                       8   
2 B              186             36.6                       8.64
3 C              162             32.2                       8.4 </code></pre>
</div>
</div>
<p>Viendo los resultados de las medias en la tabla podemos hacer las siguientes observaciones:</p>
<p>Ventas media:</p>
<p>La Marca B tiene las mayores ventas (186), mientras que la Marca A tiene las menores (144). Esto sugiere que la Marca B podría tener un mejor rendimiento en el mercado en términos de ventas en comparación con las otras dos marcas. La Marca C ocupa un lugar intermedio con 162.</p>
<p>Publicidad media:</p>
<p>La inversión en Publicidad sigue una tendencia similar a la de las ventas. La Marca B nuevamente es la que más gasta en publicidad, con un valor promedio de 36.6. La Marca A es la que menos invierte (28.2), mientras que la Marca C se encuentra entre ambas con un gasto promedio de 32.2.</p>
<p>Satisfacción del cliente media:</p>
<p>En términos de Satisfacción del cliente, la Marca B también lidera con un valor promedio de 8.64, seguida de cerca por la Marca C con 8.40. La Marca A tiene el valor más bajo de satisfacción (8.00).</p>
<p>Comentarios Generales:</p>
<p>Parece que la Marca B es la que mejor se posiciona en todos los aspectos: tiene las mayores ventas, la mayor inversión en publicidad y también la mayor satisfacción del cliente. Esto podría sugerir que su estrategia de mayor inversión en publicidad está correlacionada positivamente tanto con las ventas como con la satisfacción del cliente.</p>
<p>La Marca A parece estar en una situación más desfavorable en comparación con las otras dos marcas, mostrando menores niveles de ventas, menor inversión en publicidad y una menor satisfacción del cliente.</p>
<p>La Marca C ocupa una posición intermedia, con niveles de ventas, publicidad y satisfacción del cliente por debajo de la Marca B, pero mejores que los de la Marca A.</p>
<p>Finalmente, calculemos la matriz de correlaciones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>correlaciones <span class="ot">&lt;-</span> data_analisis2 <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Marca) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_map</span>(<span class="sc">~</span> <span class="fu">cor</span>(.x <span class="sc">%&gt;%</span> <span class="fu">select</span>(Ventas, Publicidad, Satisfaccion_cliente)))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>correlaciones</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
                        Ventas Publicidad Satisfaccion_cliente
Ventas               1.0000000  0.9576501            0.9553404
Publicidad           0.9576501  1.0000000            0.9287223
Satisfaccion_cliente 0.9553404  0.9287223            1.0000000

[[2]]
                        Ventas Publicidad Satisfaccion_cliente
Ventas               1.0000000  0.9952718            0.9889125
Publicidad           0.9952718  1.0000000            0.9985800
Satisfaccion_cliente 0.9889125  0.9985800            1.0000000

[[3]]
                        Ventas Publicidad Satisfaccion_cliente
Ventas               1.0000000  0.9974114            0.9864109
Publicidad           0.9974114  1.0000000            0.9926943
Satisfaccion_cliente 0.9864109  0.9926943            1.0000000</code></pre>
</div>
</div>
<p>En todos los casos las correlaciones entre pares de variables haciendo la separación por marcas dan positivo, entonces tenemos que para cada par de variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> si <span class="math inline">\(x_i &gt; x_j\)</span> entonces <span class="math inline">\(y_i\)</span> tiende a ser más grande que <span class="math inline">\(y_j\)</span></p>
</section>
</section>
<section id="apartado-7" class="level3">
<h3 class="anchored" data-anchor-id="apartado-7">Apartado 7</h3>
<p>Utiliza la librería <code>ggcorrplot</code> para visualizar las matrices de correlaciones para cada marca de productos mediante mapas de calor que muestren solo las matrices triangulares inferiores. Para la marca A presenta los resultados con <code>method = "square"</code>, para las marca B con <code>method = "circle"</code> y, para la marca C con <code>method = "circle"</code> pero especificando tres cifras decimales. Comenta los resultados obtenidos e indica cuál de los métodos te parece más apropiado para interpretar estos datos.</p>
<section id="respuesta-6" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-6">Respuesta</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar por cada marca y seleccionar las variables cuantitativas</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>data_A <span class="ot">&lt;-</span> data_analisis2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marca <span class="sc">==</span> <span class="st">"A"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Ventas, Publicidad, Satisfaccion_cliente)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>data_B <span class="ot">&lt;-</span> data_analisis2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marca <span class="sc">==</span> <span class="st">"B"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Ventas, Publicidad, Satisfaccion_cliente)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>data_C <span class="ot">&lt;-</span> data_analisis2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marca <span class="sc">==</span> <span class="st">"C"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Ventas, Publicidad, Satisfaccion_cliente)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular las matrices de correlación</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>cor_A <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_A)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>cor_B <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_B)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>cor_C <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_C)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Marca A:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(cor_A, <span class="at">method =</span> <span class="st">"square"</span>, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">lab =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica3_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Marca B:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(cor_B, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">lab =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica3_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Marca C:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(cor_C, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">lab =</span> <span class="cn">TRUE</span>, <span class="at">lab_size =</span> <span class="dv">4</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El método “square” aplicado a la Marca A, es adecuado cuando nos interesa principalmente la precisión numérica y comparar fácilmente las magnitudes de las correlaciones, ya que los cuadros proporcionan una comparación directa y rápida.</p>
<p>El método “circle” aplicado a las Marcas B y C, es adecuado si valoras la visualización estética y la interpretación gráfica intuitiva de la magnitud de las correlaciones. Sin embargo, su uso podría ser menos adecuado si las correlaciones son muy similares, ya que el tamaño de los círculos puede ser difícil de diferenciar en esos casos.</p>
<p>En el caso de la Marca C, mostrar tres decimales proporciona mayor precisión, lo que puede ser útil cuando necesitas un análisis más detallado de las correlaciones. Si las diferencias entre las correlaciones son pequeñas, este ajuste es importante para hacer un análisis más fino.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>